data:
  in_memory: 1
  num_workers: 12
dist:
  world_size: 1
logging:
  folder: /tmp/
  log_level: 1
  wandb_dryrun: 1
  wandb_project: rotation_benchmark
  wandb_run: rn50_88_epoch_mask_rotate
  wandb_batch_interval: 20
model:
  arch: resnet18
validation:
  resolution: 256
  corner_mask: 1
  random_rotate: 0
  p_flip_upright: 0
angle_testmode:
  standard: 1
  corr_up: 0
  corr_pred: 0
angleclassifier:
  freeze_base: 1
  attach_upright_classifier: 0
  attach_ang_classifier: 0
  classifier_upright: deep
  classifier_ang: deep
  angle_binsize: [lr, 1, 12, 45, 90, 180]
  loss_scope: 2
training:
  load_from: logs/rn18_load_from:_mask_norotate__classifier_upright:deep__classifier_ang:deep__/final_weights.pt
  eval_only: 1