data:
  in_memory: 1
  num_workers: 12
dist:
  world_size: 4
logging:
  folder: /tmp/
  log_level: 1
  wandb_dryrun: 1
  wandb_project: -1
  wandb_run: -1
  wandb_batch_interval: 20
lr:
  lr: 0.01
  lr_schedule_type: cyclic
model:
  arch: resnet18
resolution:
  end_ramp: 0
  max_res: 256
  min_res: 256
  start_ramp: 0
training:
  batch_size: 512
  bn_wd: 0
  distributed: 1
  epochs: 20
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 5e-5
  use_blurpool: 1
  corner_mask: 1
  random_rotate: 1
  checkpoint_interval: 10
  p_flip_upright: 0
validation:
  lr_tta: false
  resolution: 256
  corner_mask: 1
  random_rotate: 1
  p_flip_upright: 0
