data:
  in_memory: 1
  num_workers: 12
  val_dataset: /cluster/data/tugg/ImageNet_ffcv/val.ffcv
  #val_dataset: /home/tugg/Documents/Datasets/ImageNet_ffcv/debug.ffcv
logging:
  log_folder: logs/eval_base_models_OxfordPet
  wandb_dryrun: 0
  wandb_project: evaluate_final_base_models_highres_OxfordPet
  wandb_run: ""
model:
  arch: resnet18
  nr_cl: 37
validation:
  resolution: 256
  use_blurpool: 1
  random_rotate: 1
  mask_corner: 1
multi_validate:
  models_folder: logs/base_models_oxfordpet
  #models_folder: /home/tugg/Documents/rotation_module/ffcv-imagenet/logs/BaseModels/BaseModels/base_models_oxfordpet
  random_runs: 3
  degree_interval: 2
  add_nonrotate_run: 0
  final_chkp_only: 1