data:
  in_memory: 1
  num_workers: 12
  #val_dataset: /home/ubuntu/ImageNet_ffcv/val.ffcv
  val_dataset: /home/tugg/Documents/Datasets/ImageNet_ffcv/debug.ffcv
logging:
  log_folder: /tmp/
  wandb_dryrun: 1
  wandb_project: rotation_base_configs
  wandb_run: ""
model:
  arch: resnet18
validation:
  resolution: 256
  use_blurpool: 1
  random_rotate: 1
  mask_corner: 1
multi_validate:
  #models_folder: /home/ubuntu/ffcv-imagenet/logs/rn18_base_configs
  models_folder: /home/tugg/Documents/rotation_module/ffcv-imagenet/logs/rn18_base_configs
  random_runs: 2