data:
  gpu: 0
  in_memory: 1
  num_workers: 12
dist:
  world_size: 1
logging:
  folder: /tmp/
  log_level: 1
  wandb_dryrun: 1
  wandb_project: rotation_benchmark
  wandb_run: rn18_4_epoch_debug
  wandb_batch_interval: 100
lr:
  lr: 0.5
  lr_peak_epoch: 2
  lr_schedule_type: cyclic
model:
  arch: resnet18
resolution:
  end_ramp: 13
  max_res: 192
  min_res: 160
  start_ramp: 11
training:
  batch_size: 26
  bn_wd: 0
  distributed: 0
  epochs: 4
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 5e-5
  use_blurpool: 1
  corner_mask: 1
  random_rotate: 1
  individual_angles: 0
  checkpoint_interval: 1
validation:
  lr_tta: true
  resolution: 256
  corner_mask: 0
  random_rotate: 0

